### ISSUE TITLE
Error: AppleScript Editor is not allowed assistive access.

### ISSUE THREAD

**Issue by mpatzer** [michael-patzer/ResetAllSimulators#4]
In OS X versions before Mavericks, UI scripting was enabled or disabled system-wide. In Mavericks, UI scripting is enabled on a per-application basis.

To resolve this error in Mavericks, you must go to your Security & Privacy preference pane in System Preferences. From there, select the Privacy tab and then Accessibility. Enable AppleScript Editor under "Allow the apps below to control your computer."

Perhaps there is a way to prompt the user to enable UI elements for AppleScript Editor, or to add a try/catch and a helpful error log.

**Comment by seesolve** [comment]
I don't have Mavericks and can't test. Is it okay if I fork and create something for you to test?

**Comment by michaelpatzer** [comment]
Yes, that'd be great!
