### ISSUE TITLE
System Events got an error: Can’t get button "Reset" of window 1 of process "iPhone Simulator".

### ISSUE THREAD

**Issue by mpatzer** [michael-patzer/ResetAllSimulators#5]
Every other time I run the script, I receive this error message.

**Comment by seesolve** [comment]
Sometimes a small delay after a UI interaction helps with these kinds of hiccups. You are selecting a menu item first. You may need to give it time to generate the Reset button you want to click. I suggest inserting a `delay 0.8` line right before `tell window 1`.
